### ISSUE TITLE
uninitialized constant RedmineDmsf::Patches::ProjectPatch::DmsfFolder (NameError)

### ISSUE THREAD

**Issue by rainecc** [danmunn/redmine_dmsf#250]
Copied to the plugins directory but redmine will no longer start. Error is: 

uninitialized constant RedmineDmsf::Patches::ProjectPatch::DmsfFolder (NameError)

First few lines of the call stack are:

/var/external/asset/shared/redmine-2.5.1/plugins/redmine_dmsf-master/lib/redmine_dmsf/patches/project_patch.rb:39:in `block in included'
  /var/external/asset/shared/redmine-2.5.1/plugins/redmine_dmsf-master/lib/redmine_dmsf/patches/project_patch.rb:29:in `class_eval'
  /var/external/asset/shared/redmine-2.5.1/plugins/redmine_dmsf-master/lib/redmine_dmsf/patches/project_patch.rb:29:in `included'
  /var/external/asset/shared/redmine-2.5.1/plugins/redmine_dmsf-master/lib/redmine_dmsf/patches/project_patch.rb:100:in `include'
  /var/external/asset/shared/redmine-2.5.1/plugins/redmine_dmsf-master/lib/redmine_dmsf/patches/project_patch.rb:100:in `block in <top (required)>'
  /usr/local/lib/ruby/gems/2.0.0/gems/activesupport-3.2.17/lib/active_support/callbacks.rb:440:in `_run__1356629954713839814__prepare__708486660785117676__callbacks'
  /usr/local/lib/ruby/gems/2.0.0/gems/activesupport-3.2.17/lib/active_support/callbacks.rb:405:in `__run_callback'
  /usr/local/lib/ruby/gems/2.0.0/gems/activesupport-3.2.17/lib/active_support/callbacks.rb:385:in `_run_prepare_callbacks'
  /usr/local/lib/ruby/gems/2.0.0/gems/activesupport-3.2.17/lib/active_support/callbacks.rb:81:in `run_callbacks'
  /usr/local/lib/ruby/gems/2.0.0/gems/actionpack-3.2.17/lib/action_dispatch/middleware/reloader.rb:74:in `prepare!'
  /usr/local/lib/ruby/gems/2.0.0/gems/actionpack-3.2.17/lib/action_dispatch/middleware/reloader.rb:48:in `prepare!'
  /usr/local/lib/ruby/gems/2.0.0/gems/railties-3.2.17/lib/rails/application/finisher.rb:47:in `block in <module:Finisher>'
  /usr/local/lib/ruby/gems/2.0.0/gems/railties-3.2.17/lib/rails/initializable.rb:30:in `instance_exec'
  /usr/local/lib/ruby/gems/2.0.0/gems/railties-3.2.17/lib/rails/initializable.rb:30:in `run'
  /usr/local/lib/ruby/gems/2.0.0/gems/railties-3.2.17/lib/rails/initializable.rb:55:in `block in run_initializers'
  /usr/local/lib/ruby/gems/2.0.0/gems/railties-3.2.17/lib/rails/initializable.rb:54:in `each'
  /usr/local/lib/ruby/gems/2.0.0/gems/railties-3.2.17/lib/rails/initializable.rb:54:in `run_initializers'
  /usr/local/lib/ruby/gems/2.0.0/gems/railties-3.2.17/lib/rails/application.rb:136:in `initialize!'
  /usr/local/lib/ruby/gems/2.0.0/gems/railties-3.2.17/lib/rails/railtie/configurable.rb:30:in `method_missing'
  /var/external/asset/shared/redmine-2.5.1/config/environment.rb:14:in `<top (required)>'
  config.ru:3:in `require'

**Comment by eLvErDe** [comment]
I can confirm this issue, it breaks Redmine completely. Any idea ?

**Comment by picman** [comment]
Fixed. Thank you for the bug report.

**Comment by ronlinet** [comment]
Issue is still there. I have cloned the the git and my installation stuck with : 

rake aborted!
uninitialized constant RedmineDmsf::Patches::ProjectPatch::DmsfFolder
Tasks: TOP => redmine:plugins:migrate => environment
(See full trace by running task with --trace)

**Comment by picman** [comment]
Do you have the branch devel-1.5.1?

**Comment by ronlinet** [comment]
No I have simply checked out the git branch from project page. Do you plan to include the fix into stable release?

**Comment by picman** [comment]
No I don't. Please checkout devel-1.5.1 branch.
