### ISSUE TITLE
WebDAV: Files disappearing in mounted drive when you delete a folder created through Windows file explorer

### ISSUE THREAD

**Issue by Keltrex** [danmunn/redmine_dmsf#334]
Possible bug

I recently was able to use dmsf webdav on my bitnami windows install of redmine, but if I create a folder using file explorer and then delete it, everything in that folder disappears. The files are not erased, however, just unable to be viewed in explorer. They are still able to be accessed normally through redmine, and if you put in the correct path in file explorer, they will open as well. I have tried remounting the drive, which did nothing, and also mounting it on another computer, which also shows no files or folders in the locations I deleted a folder. I can still see the contents of other folders that I have not done that in, but after some testing I can confirm that deleting a folder made in file explorer is the cause of this. I am still very new to redmine (and honestly, IT in general) so any help is appreciated!

I am running Bitnami Redmine Stack 2.6.1-0 on a Windows 7 machine in a production environment.
I am also running DMSF version 1.4.9

This is the log from me making a file, creating a folder that I will delete, adding two other files and then deleting the folder:

<code>Started PROPFIND "/redmine/dmsf/webdav/information-technology" for 127.0.0.1 at 2015-01-12 14:49:45 -0800
Started PROPFIND "/redmine/dmsf/webdav/information-technology/Test%20Folder%201/desktop.ini" for 127.0.0.1 at 2015-01-12 14:49:46 -0800
Started PROPFIND "/redmine/dmsf/webdav/information-technology/Test%20Folder%201/folder.jpg" for 127.0.0.1 at 2015-01-12 14:49:46 -0800
Started PROPFIND "/redmine/dmsf/webdav/information-technology/Test%20Folder%201/folder.gif" for 127.0.0.1 at 2015-01-12 14:49:46 -0800
Started PROPFIND "/redmine/dmsf/webdav/information-technology/Test%20Folder%201" for 127.0.0.1 at 2015-01-12 14:49:46 -0800
Started PROPFIND "/redmine/dmsf/webdav/information-technology/Test%20Folder%201" for 127.0.0.1 at 2015-01-12 14:49:46 -0800
Started PROPFIND "/redmine/dmsf/webdav/information-technology" for 127.0.0.1 at 2015-01-12 14:49:53 -0800
Started PROPFIND "/redmine/dmsf/webdav/information-technology/Test%20Folder%201/New%20folder" for 127.0.0.1 at 2015-01-12 14:49:53 -0800
Started MKCOL "/redmine/dmsf/webdav/information-technology/Test%20Folder%201/New%20folder" for 127.0.0.1 at 2015-01-12 14:49:53 -0800
Started PROPPATCH "/redmine/dmsf/webdav/information-technology/Test%20Folder%201/New%20folder" for 127.0.0.1 at 2015-01-12 14:49:53 -0800
Started PROPFIND "/redmine/dmsf/webdav/information-technology/Test%20Folder%201/New%20folder/desktop.ini" for 127.0.0.1 at 2015-01-12 14:49:53 -0800
Started PROPFIND "/redmine/dmsf/webdav/information-technology/test%20folder%201/.hg" for 127.0.0.1 at 2015-01-12 14:49:53 -0800
Started PROPFIND "/redmine/dmsf/webdav/information-technology/Test%20Folder%201/New%20folder/folder.jpg" for 127.0.0.1 at 2015-01-12 14:49:53 -0800
Started PROPFIND "/redmine/dmsf/webdav/information-technology/Test%20Folder%201/New%20folder/folder.gif" for 127.0.0.1 at 2015-01-12 14:49:53 -0800
Started PROPFIND "/redmine/dmsf/webdav/information-technology/Test%20Folder%201/New%20folder" for 127.0.0.1 at 2015-01-12 14:49:53 -0800
Started PROPFIND "/redmine/dmsf/webdav/information-technology" for 127.0.0.1 at 2015-01-12 14:50:00 -0800
Started PROPFIND "/redmine/dmsf/webdav/information-technology/Test%20Folder%201/New%20folder" for 127.0.0.1 at 2015-01-12 14:50:00 -0800
Started MOVE "/redmine/dmsf/webdav/information-technology/Test%20Folder%201/New%20folder" for 127.0.0.1 at 2015-01-12 14:50:00 -0800
Started PROPFIND "/redmine/dmsf/webdav/information-technology/Test%20Folder%201/New%20folder" for 127.0.0.1 at 2015-01-12 14:50:00 -0800
Started PROPFIND "/redmine/dmsf/webdav/information-technology" for 127.0.0.1 at 2015-01-12 14:50:03 -0800
Started PROPFIND "/redmine/dmsf/webdav/information-technology/Test%20Folder%201" for 127.0.0.1 at 2015-01-12 14:50:04 -0800
Started PROPFIND "/redmine/dmsf/webdav/information-technology" for 127.0.0.1 at 2015-01-12 14:50:17 -0800
Started PROPFIND "/redmine/dmsf/webdav/information-technology/Test%20Folder%201/KB.exe" for 127.0.0.1 at 2015-01-12 14:50:17 -0800
Started PUT "/redmine/dmsf/webdav/information-technology/Test%20Folder%201/KB.exe" for 127.0.0.1 at 2015-01-12 14:50:17 -0800
Started LOCK "/redmine/dmsf/webdav/information-technology/Test%20Folder%201/KB.exe" for 127.0.0.1 at 2015-01-12 14:50:17 -0800
Started GET "/redmine/dmsf/webdav/information-technology/Test%20Folder%201/KB.exe" for 127.0.0.1 at 2015-01-12 14:50:17 -0800
Started PUT "/redmine/dmsf/webdav/information-technology/Test%20Folder%201/KB.exe" for 127.0.0.1 at 2015-01-12 14:50:18 -0800
Started PROPPATCH "/redmine/dmsf/webdav/information-technology/Test%20Folder%201/KB.exe" for 127.0.0.1 at 2015-01-12 14:50:19 -0800
Started PROPPATCH "/redmine/dmsf/webdav/information-technology/Test%20Folder%201/KB.exe" for 127.0.0.1 at 2015-01-12 14:50:19 -0800
Started UNLOCK "/redmine/dmsf/webdav/information-technology/Test%20Folder%201/KB.exe" for 127.0.0.1 at 2015-01-12 14:50:19 -0800
Started PROPFIND "/redmine/dmsf/webdav/information-technology/Test%20Folder%201" for 127.0.0.1 at 2015-01-12 14:50:19 -0800
Started PROPFIND "/redmine/dmsf/webdav/information-technology/Test%20Folder%201/ui/SwDRM.dll" for 127.0.0.1 at 2015-01-12 14:50:19 -0800
Started PROPFIND "/redmine/dmsf/webdav/information-technology/Test%20Folder%201/Thumbs.db" for 127.0.0.1 at 2015-01-12 14:50:19 -0800
Started PROPFIND "/redmine/dmsf/webdav/information-technology/Test%20Folder%201/KB.exe.Manifest" for 127.0.0.1 at 2015-01-12 14:50:19 -0800
Started PROPFIND "/redmine/dmsf/webdav/information-technology/Test%20Folder%201" for 127.0.0.1 at 2015-01-12 14:50:19 -0800
Started PROPFIND "/redmine/dmsf/webdav/information-technology/Test%20Folder%201" for 127.0.0.1 at 2015-01-12 14:50:19 -0800
Started GET "/redmine/dmsf/webdav/information-technology/test%20folder%201/kb.exe" for 127.0.0.1 at 2015-01-12 14:50:19 -0800
Started PROPFIND "/redmine/dmsf/webdav/information-technology/test%20folder%201/kb.exe.DLL" for 127.0.0.1 at 2015-01-12 14:50:19 -0800
Started PROPFIND "/redmine/dmsf/webdav/information-technology/Test%20Folder%201/KB.exe.DLL" for 127.0.0.1 at 2015-01-12 14:50:19 -0800
Started PROPFIND "/redmine/dmsf/webdav/information-technology" for 127.0.0.1 at 2015-01-12 14:50:25 -0800
Started PROPFIND "/redmine/dmsf/webdav/information-technology" for 127.0.0.1 at 2015-01-12 14:50:25 -0800
Started PROPFIND "/redmine/dmsf/webdav/information-technology/Test%20Folder%201/BuildSQLUpdatesInserts.exe" for 127.0.0.1 at 2015-01-12 14:50:25 -0800
Started PUT "/redmine/dmsf/webdav/information-technology/Test%20Folder%201/BuildSQLUpdatesInserts.exe" for 127.0.0.1 at 2015-01-12 14:50:25 -0800
Started LOCK "/redmine/dmsf/webdav/information-technology/Test%20Folder%201/BuildSQLUpdatesInserts.exe" for 127.0.0.1 at 2015-01-12 14:50:25 -0800
Started GET "/redmine/dmsf/webdav/information-technology/Test%20Folder%201/BuildSQLUpdatesInserts.exe" for 127.0.0.1 at 2015-01-12 14:50:25 -0800
Started PUT "/redmine/dmsf/webdav/information-technology/Test%20Folder%201/BuildSQLUpdatesInserts.exe" for 127.0.0.1 at 2015-01-12 14:50:27 -0800
Started PROPPATCH "/redmine/dmsf/webdav/information-technology/Test%20Folder%201/BuildSQLUpdatesInserts.exe" for 127.0.0.1 at 2015-01-12 14:50:27 -0800
Started PROPPATCH "/redmine/dmsf/webdav/information-technology/Test%20Folder%201/BuildSQLUpdatesInserts.exe" for 127.0.0.1 at 2015-01-12 14:50:27 -0800
Started UNLOCK "/redmine/dmsf/webdav/information-technology/Test%20Folder%201/BuildSQLUpdatesInserts.exe" for 127.0.0.1 at 2015-01-12 14:50:27 -0800
Started PROPFIND "/redmine/dmsf/webdav/information-technology/.hg" for 127.0.0.1 at 2015-01-12 14:50:27 -0800
Started PROPFIND "/redmine/dmsf/webdav/information-technology/Test%20Folder%201" for 127.0.0.1 at 2015-01-12 14:50:27 -0800
Started PROPFIND "/redmine/dmsf/webdav/information-technology/Test%20Folder%201" for 127.0.0.1 at 2015-01-12 14:50:28 -0800
Started PROPFIND "/redmine/dmsf/webdav/information-technology/Test%20Folder%201/BuildSQLUpdatesInserts.exe.Manifest" for 127.0.0.1 at 2015-01-12 14:50:28 -0800
Started PROPFIND "/redmine/dmsf/webdav/information-technology/Test%20Folder%201" for 127.0.0.1 at 2015-01-12 14:50:28 -0800
Started GET "/redmine/dmsf/webdav/information-technology/test%20folder%201/buildsqlupdatesinserts.exe" for 127.0.0.1 at 2015-01-12 14:50:28 -0800
Started PROPFIND "/redmine/dmsf/webdav/information-technology/test%20folder%201/buildsqlupdatesinserts.exe.DLL" for 127.0.0.1 at 2015-01-12 14:50:28 -0800
Started PROPFIND "/redmine/dmsf/webdav/information-technology/Test%20Folder%201/BuildSQLUpdatesInserts.exe.DLL" for 127.0.0.1 at 2015-01-12 14:50:28 -0800
Started PROPFIND "/redmine/dmsf/webdav/information-technology" for 127.0.0.1 at 2015-01-12 14:50:30 -0800
Started PROPFIND "/redmine/dmsf/webdav/information-technology/Test%20Folder%201" for 127.0.0.1 at 2015-01-12 14:50:32 -0800
Started PROPFIND "/redmine/dmsf/webdav/information-technology/Test%20Folder%201/Folder%20to%20be%20deleted/desktop.ini" for 127.0.0.1 at 2015-01-12 14:50:33 -0800
Started PROPFIND "/redmine/dmsf/webdav/information-technology/Test%20Folder%201/Folder%20to%20be%20deleted/folder.jpg" for 127.0.0.1 at 2015-01-12 14:50:33 -0800
Started PROPFIND "/redmine/dmsf/webdav/information-technology/Test%20Folder%201/Folder%20to%20be%20deleted/folder.gif" for 127.0.0.1 at 2015-01-12 14:50:33 -0800
Started PROPFIND "/redmine/dmsf/webdav/information-technology/Test%20Folder%201/Folder%20to%20be%20deleted" for 127.0.0.1 at 2015-01-12 14:50:33 -0800
Started PROPFIND "/redmine/dmsf/webdav/information-technology" for 127.0.0.1 at 2015-01-12 14:50:36 -0800
Started PROPFIND "/redmine/dmsf/webdav/information-technology/Test%20Folder%201/Folder%20to%20be%20deleted" for 127.0.0.1 at 2015-01-12 14:50:42 -0800
Started PROPFIND "/redmine/dmsf/webdav/information-technology/Test%20Folder%201/Folder%20to%20be%20deleted" for 127.0.0.1 at 2015-01-12 14:50:42 -0800
Started DELETE "/redmine/dmsf/webdav/information-technology/Test%20Folder%201/Folder%20to%20be%20deleted" for 127.0.0.1 at 2015-01-12 14:50:42 -0800
Started PROPFIND "/redmine/dmsf/webdav/information-technology" for 127.0.0.1 at 2015-01-12 14:50:43 -0800
Started PROPFIND "/redmine/dmsf/webdav/information-technology/Programs" for 127.0.0.1 at 2015-01-12 14:50:44 -0800
Started PROPFIND "/redmine/dmsf/webdav/information-technology/Test%20Folder%201" for 127.0.0.1 at 2015-01-12 14:50:45 -0800

<code>NoMethodError (undefined method `xmlschema' for DAV4Rack::HTTPStatus::NotFound:Class):
  dav4rack (0.3.0) lib/dav4rack/resource.rb:367:in `get_property'
  plugins/redmine_dmsf/lib/redmine_dmsf/webdav/dmsf_resource.rb:558:in `get_property'
  dav4rack (0.3.0) lib/dav4rack/resource.rb:116:in `method_missing'
  plugins/redmine_dmsf/lib/redmine_dmsf/webdav/resource_proxy.rb:151:in `get_property'
  dav4rack (0.3.0) lib/dav4rack/resource.rb:116:in `method_missing'
  dav4rack (0.3.0) lib/dav4rack/controller.rb:510:in `block in get_properties'
  dav4rack (0.3.0) lib/dav4rack/controller.rb:508:in `each'
  dav4rack (0.3.0) lib/dav4rack/controller.rb:508:in `get_properties'
  plugins/redmine_dmsf/lib/redmine_dmsf/webdav/controller.rb:67:in `block (3 levels) in propfind'
  nokogiri-1.6.3.1-x86 (mingw32) lib/nokogiri/xml/builder.rb:391:in `call'
  nokogiri-1.6.3.1-x86 (mingw32) lib/nokogiri/xml/builder.rb:391:in `insert'
  nokogiri-1.6.3.1-x86 (mingw32) lib/nokogiri/xml/builder.rb:375:in `method_missing'
  plugins/redmine_dmsf/lib/redmine_dmsf/webdav/controller.rb:61:in `block (2 levels) in propfind'
  plugins/redmine_dmsf/lib/redmine_dmsf/webdav/controller.rb:60:in `each'
  plugins/redmine_dmsf/lib/redmine_dmsf/webdav/controller.rb:60:in `block in propfind'
  dav4rack (0.3.0) lib/dav4rack/controller.rb:468:in `block (2 levels) in render_xml'
  nokogiri-1.6.3.1-x86 (mingw32) lib/nokogiri/xml/builder.rb:391:in `call'
  nokogiri-1.6.3.1-x86 (mingw32) lib/nokogiri/xml/builder.rb:391:in `insert'
  nokogiri-1.6.3.1-x86 (mingw32) lib/nokogiri/xml/builder.rb:375:in `method_missing'
  dav4rack (0.3.0) lib/dav4rack/controller.rb:465:in `block in render_xml'
  nokogiri-1.6.3.1-x86 (mingw32) lib/nokogiri/xml/builder.rb:293:in `initialize'
  dav4rack (0.3.0) lib/dav4rack/controller.rb:464:in `new'
  dav4rack (0.3.0) lib/dav4rack/controller.rb:464:in `render_xml'
  dav4rack (0.3.0) lib/dav4rack/controller.rb:487:in `multistatus'
  plugins/redmine_dmsf/lib/redmine_dmsf/webdav/controller.rb:59:in `propfind'
  dav4rack (0.3.0) lib/dav4rack/handler.rb:30:in `call'
  journey (1.0.4) lib/journey/router.rb:68:in `block in call'
  journey (1.0.4) lib/journey/router.rb:56:in `each'
  journey (1.0.4) lib/journey/router.rb:56:in `call'
  actionpack (3.2.19) lib/action_dispatch/routing/route_set.rb:608:in `call'
  rack-openid (1.4.1) lib/rack/openid.rb:99:in `call'
  request_store (1.0.5) lib/request_store/middleware.rb:9:in `call'
  actionpack (3.2.19) lib/action_dispatch/middleware/best_standards_support.rb:17:in `call'
  rack (1.4.5) lib/rack/etag.rb:23:in `call'
  rack (1.4.5) lib/rack/conditionalget.rb:35:in `call'
  actionpack (3.2.19) lib/action_dispatch/middleware/head.rb:14:in `call'
  actionpack (3.2.19) lib/action_dispatch/middleware/params_parser.rb:21:in `call'
  plugins/redmine_dmsf/lib/redmine_dmsf/webdav/no_parse.rb:33:in `call'
  actionpack (3.2.19) lib/action_dispatch/middleware/flash.rb:242:in `call'
  rack (1.4.5) lib/rack/session/abstract/id.rb:210:in `context'
  rack (1.4.5) lib/rack/session/abstract/id.rb:205:in `call'
  actionpack (3.2.19) lib/action_dispatch/middleware/cookies.rb:341:in `call'
  activerecord (3.2.19) lib/active_record/query_cache.rb:64:in `call'
  activerecord (3.2.19) lib/active_record/connection_adapters/abstract/connection_pool.rb:479:in `call'
  actionpack (3.2.19) lib/action_dispatch/middleware/callbacks.rb:28:in `block in call'
  activesupport (3.2.19) lib/active_support/callbacks.rb:405:in `_run__1036207371__call__725770598__callbacks'
  activesupport (3.2.19) lib/active_support/callbacks.rb:405:in `__run_callback'
  activesupport (3.2.19) lib/active_support/callbacks.rb:385:in `_run_call_callbacks'
  activesupport (3.2.19) lib/active_support/callbacks.rb:81:in `run_callbacks'
  actionpack (3.2.19) lib/action_dispatch/middleware/callbacks.rb:27:in `call'
  actionpack (3.2.19) lib/action_dispatch/middleware/remote_ip.rb:31:in `call'
  actionpack (3.2.19) lib/action_dispatch/middleware/debug_exceptions.rb:16:in `call'
  actionpack (3.2.19) lib/action_dispatch/middleware/show_exceptions.rb:56:in `call'
  railties (3.2.19) lib/rails/rack/logger.rb:32:in `call_app'
  railties (3.2.19) lib/rails/rack/logger.rb:16:in `block in call'
  activesupport (3.2.19) lib/active_support/tagged_logging.rb:22:in `tagged'
  railties (3.2.19) lib/rails/rack/logger.rb:16:in `call'
  actionpack (3.2.19) lib/action_dispatch/middleware/request_id.rb:22:in `call'
  rack (1.4.5) lib/rack/methodoverride.rb:21:in `call'
  rack (1.4.5) lib/rack/runtime.rb:17:in `call'
  activesupport (3.2.19) lib/active_support/cache/strategy/local_cache.rb:72:in `call'
  rack (1.4.5) lib/rack/lock.rb:15:in `call'
  actionpack (3.2.19) lib/action_dispatch/middleware/static.rb:63:in `call'
  rack-cache (1.2) lib/rack/cache/context.rb:136:in `forward'
  rack-cache (1.2) lib/rack/cache/context.rb:143:in `pass'
  rack-cache (1.2) lib/rack/cache/context.rb:155:in `invalidate'
  rack-cache (1.2) lib/rack/cache/context.rb:71:in `call!'
  rack-cache (1.2) lib/rack/cache/context.rb:51:in `call'
  railties (3.2.19) lib/rails/engine.rb:484:in `call'
  railties (3.2.19) lib/rails/application.rb:231:in `call'
  railties (3.2.19) lib/rails/railtie/configurable.rb:30:in `method_missing'
  rack (1.4.5) lib/rack/urlmap.rb:64:in `block in call'
  rack (1.4.5) lib/rack/urlmap.rb:49:in `each'
  rack (1.4.5) lib/rack/urlmap.rb:49:in `call'
  thin-1.6.1-x86 (mingw32) lib/thin/connection.rb:82:in `block in pre_process'
  thin-1.6.1-x86 (mingw32) lib/thin/connection.rb:80:in `catch'
  thin-1.6.1-x86 (mingw32) lib/thin/connection.rb:80:in `pre_process'
  thin-1.6.1-x86 (mingw32) lib/thin/connection.rb:55:in `process'
  thin-1.6.1-x86 (mingw32) lib/thin/connection.rb:41:in `receive_data'
  eventmachine-1.0.3-x86 (mingw32) lib/eventmachine.rb:187:in `run_machine'
  eventmachine-1.0.3-x86 (mingw32) lib/eventmachine.rb:187:in `run'
  thin-1.6.1-x86 (mingw32) lib/thin/backends/base.rb:73:in `start'
  thin-1.6.1-x86 (mingw32) lib/thin/server.rb:162:in `start'
  thin-1.6.1-x86 (mingw32) lib/thin/controllers/controller.rb:87:in `start'
  thin-1.6.1-x86 (mingw32) lib/thin/runner.rb:200:in `run_command'
  thin-1.6.1-x86 (mingw32) lib/thin/runner.rb:156:in `run!'
  thin-1.6.1-x86 (mingw32) bin/thin:6:in `<top (required)>'
  bin/thin:16:in `load'
  bin/thin:16:in `<main>'</code>

<code>Started PROPFIND "/redmine/dmsf/webdav/information-technology/Test%20Folder%201" for 127.0.0.1 at 2015-01-12 14:50:45 -0800
</code>

**Comment by Keltrex** [comment]
Huh, I just checked the webdav folder from the browser (...redmine/dmsf/webdav/project-id), and it still shows ALL files, including deleted ones (which aren't accessible obviously). Here is a screenshot:

![webdav_problem](https://cloud.githubusercontent.com/assets/10455797/5713165/fded9c98-9a6d-11e4-8085-f9229782762f.jpg)

**Comment by eurodba** [comment]
Exactly the same situation - DMSF plugin in Redmine.
Also, I found following detail - when I you use Total Commander's plugin WebDav (http://ghisler.fileburst.com/fsplugins/webdav.zip from page http://www.ghisler.com/plugins.htm), it does not allow to traverse folder with spaces in the name (however IE/Chrome does it without any problems). I have asked question on the TC forum (http://www.ghisler.ch/board/viewtopic.php?t=40800, at the bottom) - and plugin's author prove, that his plugin realized WebDav protocol correctly, and spaces in filenames/folders his plugin processes also without any issues.
So, I start to think that problem is on server side, but not in DMSF itself, but in DAV4Rac Ruby gem, which actually realized WebDav functionality.

**Comment by Keltrex** [comment]
That's actually really interesting! I'll start to check into DAV4Rack and see if I can find something.
Thanks for the info!

**Comment by eurodba** [comment]
Hi! Do you have any news regarding current issue? I still can't understand - is there issue in DMSF, or that is definitely coming from Dav4Rack gem? If second - then maybe we have problems, as last commit in Dav4Rack was 2 years ago (https://github.com/chrisroberts/dav4rack), however, seems author "is alive" (other repositories shows activity).
I ask, because I recognize WebDav access to DMSF as a "killer feature", so, I will be happy if it would be stable and not so buggy (as it is now unfortunately).

**Comment by Keltrex** [comment]
I searched through dav4racks issues and tried to dig into the code, but so far I've come up with nothing. Perhaps we should try to contact Chris and hopefully get help on this.

**Comment by eurodba** [comment]
Ok, I can manage that, as I want to help - you are doing great job, your plugin is very useful. I will then combine together all available info, screenshots, logs etc. and will open ticket in Dav4Rack's issue tracker.

—
Отправлено из Mailbox

**Comment by eurodba** [comment]
Issue created in Chris's repository: https://github.com/chrisroberts/dav4rack/issues/61

**Comment by picman** [comment]
If someone has got sufficient skills it's not difficult to override any class from Dav4Rack and fix problems in scope of this plugin. The effort to wake up Dav4Rack development may not meet with success.

**Comment by eurodba** [comment]
It will be definitely not me, unfortunately - I am Oracle DBA....

**Comment by Keltrex** [comment]
My skills are basic at best, so unfortunately I won't be of much help either.

**Comment by Keltrex** [comment]
It looks like Chris responded to your post eurodba! He says that he plans to work on it sometime next week.

**Comment by eurodba** [comment]
Hi Keltrex, yes, I have seen yesterday! I prepare now answer. So, "fingers cross" - at least now we have hope, that we are not alone, one-on-one with problematic gem and later or sooner, all will be resolved!

**Comment by Keltrex** [comment]
After testing over the last few days, I have decided to close this issue as it appears to have been resolved. I can create and delete files at my whim without anything being hidden or randomly deleted. Thanks to all who helped!

**Comment by eurodba** [comment]
Hi, OK, as you wish. For myself I still does not made final decision about current issue - do I understand for 100% what is happening, or not. Thing is - I also can traverse some folders via WebDav, using Windows Explorer and Total Commander's WebDav plugin. But some folders - not. So, currently I do not understand logic, when all is working fine, when plugin crashed.

In case I will finally found reason/solution - will post here details for everyone who gets into similar situation, will be able to find answers.

Anyway, thanks a lot!
