### ISSUE TITLE
Unable to properly uninstall the plugin

### ISSUE THREAD

**Issue by topkool** [danmunn/redmine_dmsf#371]
Since the fix for #366, new updates have been added, and the issue about uninstallation comes back:

~~~
(in /usr/share/redmine-3.0.1)
Migrating redmine_dmsf (DMSF)...
== 20150202010301 AddUserToLinks: reverting ===================================
-- remove_column(:dmsf_links, :user_id)
   -> 0.2553s
== 20150202010301 AddUserToLinks: reverted (0.2554s) ==========================

== 20150130052716 AddExternal: reverting ======================================
-- change_column(:dmsf_links, :target_id, :integer, {:null=>false})
   -> 0.2108s
-- remove_column(:dmsf_links, :external_url)
   -> 0.2149s
== 20150130052716 AddExternal: reverted (0.4259s) =============================

== 20150120152101 NotificationsNullable: reverting ============================
== 20150120152101 NotificationsNullable: reverted (0.0000s) ===================

== 20141205143001 RemoveUniquenessFromWf: reverting ===========================
-- add_index(:dmsf_workflows, [:name], {:unique=>true})
   -> 0.1587s
== 20141205143001 RemoveUniquenessFromWf: reverted (0.1588s) ==================

== 20141015132701 RemoveFolderFromRevision: reverting =========================
-- add_column(:dmsf_file_revisions, :dmsf_folder_id, :integer, {:null=>true})
   -> 0.2421s
== 20141015132701 RemoveFolderFromRevision: reverted (0.4656s) ================

== 20141013102501 RemoveProjectFromRevision: reverting ========================
-- add_column(:dmsf_file_revisions, :project_id, :integer, {:null=>true})
   -> 0.2587s
-- change_column(:dmsf_file_revisions, :project_id, :integer, {:null=>false})
rake aborted!
An error has occurred, all later migrations canceled:

Mysql2::Error: Data truncated for column 'project_id' at row 1: ALTER TABLE `dmsf_file_revisions` CHANGE `project_id` `project_id` int(11) NOT NULL/usr/local/rvm/gems/ruby-2.1.5/gems/activerecord-4.2.0/lib/active_record/connection_adapters/abstract_mysql_adapter.rb:299:in `query'
/usr/local/rvm/gems/ruby-2.1.5/gems/activerecord-4.2.0/lib/active_record/connection_adapters/abstract_mysql_adapter.rb:299:in `block in execute'
/usr/local/rvm/gems/ruby-2.1.5/gems/activerecord-4.2.0/lib/active_record/connection_adapters/abstract_adapter.rb:466:in `block in log'
/usr/local/rvm/gems/ruby-2.1.5/gems/activesupport-4.2.0/lib/active_support/notifications/instrumenter.rb:20:in `instrument'
/usr/local/rvm/gems/ruby-2.1.5/gems/activerecord-4.2.0/lib/active_record/connection_adapters/abstract_adapter.rb:460:in `log'
/usr/local/rvm/gems/ruby-2.1.5/gems/activerecord-4.2.0/lib/active_record/connection_adapters/abstract_mysql_adapter.rb:299:in `execute'
/usr/local/rvm/gems/ruby-2.1.5/gems/activerecord-4.2.0/lib/active_record/connection_adapters/mysql2_adapter.rb:231:in `execute'
/usr/local/rvm/gems/ruby-2.1.5/gems/activerecord-4.2.0/lib/active_record/connection_adapters/abstract_mysql_adapter.rb:517:in `change_column'
/usr/local/rvm/gems/ruby-2.1.5/gems/activerecord-4.2.0/lib/active_record/migration.rb:662:in `block in method_missing'
/usr/local/rvm/gems/ruby-2.1.5/gems/activerecord-4.2.0/lib/active_record/migration.rb:632:in `block in say_with_time'
/usr/local/rvm/gems/ruby-2.1.5/gems/activerecord-4.2.0/lib/active_record/migration.rb:632:in `say_with_time'
/usr/local/rvm/gems/ruby-2.1.5/gems/activerecord-4.2.0/lib/active_record/migration.rb:652:in `method_missing'
/usr/share/redmine-3.0.1/plugins/redmine_dmsf/db/migrate/20141013102501_remove_project_from_revision.rb:34:in `down'
/usr/local/rvm/gems/ruby-2.1.5/gems/activerecord-4.2.0/lib/active_record/migration.rb:609:in `exec_migration'
/usr/local/rvm/gems/ruby-2.1.5/gems/activerecord-4.2.0/lib/active_record/migration.rb:590:in `block (2 levels) in migrate'
/usr/local/rvm/gems/ruby-2.1.5/gems/activerecord-4.2.0/lib/active_record/migration.rb:589:in `block in migrate'
/usr/local/rvm/gems/ruby-2.1.5/gems/activerecord-4.2.0/lib/active_record/connection_adapters/abstract/connection_pool.rb:292:in `with_connection'
/usr/local/rvm/gems/ruby-2.1.5/gems/activerecord-4.2.0/lib/active_record/migration.rb:588:in `migrate'
/usr/local/rvm/gems/ruby-2.1.5/gems/activerecord-4.2.0/lib/active_record/migration.rb:765:in `migrate'
/usr/local/rvm/gems/ruby-2.1.5/gems/activerecord-4.2.0/lib/active_record/migration.rb:995:in `block in execute_migration_in_transaction'
/usr/local/rvm/gems/ruby-2.1.5/gems/activerecord-4.2.0/lib/active_record/migration.rb:1043:in `ddl_transaction'
/usr/local/rvm/gems/ruby-2.1.5/gems/activerecord-4.2.0/lib/active_record/migration.rb:994:in `execute_migration_in_transaction'
/usr/local/rvm/gems/ruby-2.1.5/gems/activerecord-4.2.0/lib/active_record/migration.rb:956:in `block in migrate'
/usr/local/rvm/gems/ruby-2.1.5/gems/activerecord-4.2.0/lib/active_record/migration.rb:952:in `each'
/usr/local/rvm/gems/ruby-2.1.5/gems/activerecord-4.2.0/lib/active_record/migration.rb:952:in `migrate'
/usr/local/rvm/gems/ruby-2.1.5/gems/activerecord-4.2.0/lib/active_record/migration.rb:827:in `down'
/usr/local/rvm/gems/ruby-2.1.5/gems/activerecord-4.2.0/lib/active_record/migration.rb:802:in `migrate'
/usr/share/redmine-3.0.1/lib/redmine/plugin.rb:474:in `migrate_plugin'
/usr/share/redmine-3.0.1/lib/redmine/plugin.rb:446:in `migrate'
/usr/share/redmine-3.0.1/lib/redmine/plugin.rb:457:in `migrate'
/usr/share/redmine-3.0.1/lib/tasks/redmine.rake:127:in `block (3 levels) in <top (required)>'
/usr/local/rvm/gems/ruby-2.1.5/bin/ruby_executable_hooks:15:in `eval'
/usr/local/rvm/gems/ruby-2.1.5/bin/ruby_executable_hooks:15:in `<main>'
Tasks: TOP => redmine:plugins:migrate
(See full trace by running task with --trace)
~~~

**Comment by picman** [comment]
Fixed. Please test it.

**Comment by topkool** [comment]
It is better, but there is still an issue.

~~~
(in /usr/share/redmine-3.0.1)
Migrating redmine_dmsf (DMSF)...
== 20150202010301 AddUserToLinks: reverting ===================================
-- remove_column(:dmsf_links, :user_id)
   -> 0.2682s
== 20150202010301 AddUserToLinks: reverted (0.2683s) ==========================

== 20150130052716 AddExternal: reverting ======================================
-- change_column(:dmsf_links, :target_id, :integer, {:null=>false})
   -> 0.2005s
-- remove_column(:dmsf_links, :external_url)
   -> 0.2016s
== 20150130052716 AddExternal: reverted (0.4022s) =============================

== 20150120152101 NotificationsNullable: reverting ============================
== 20150120152101 NotificationsNullable: reverted (0.0000s) ===================

== 20141205143001 RemoveUniquenessFromWf: reverting ===========================
-- add_index(:dmsf_workflows, [:name], {:unique=>true})
   -> 0.1978s
== 20141205143001 RemoveUniquenessFromWf: reverted (0.1979s) ==================

== 20141015132701 RemoveFolderFromRevision: reverting =========================
-- add_column(:dmsf_file_revisions, :dmsf_folder_id, :integer, {:null=>true})
   -> 0.2502s
== 20141015132701 RemoveFolderFromRevision: reverted (0.5433s) ================

== 20141013102501 RemoveProjectFromRevision: reverting ========================
-- add_column(:dmsf_file_revisions, :project_id, :integer, {:null=>true})
rake aborted!
An error has occurred, all later migrations canceled:

Mysql2::Error: Duplicate column name 'project_id': ALTER TABLE `dmsf_file_revisions` ADD `project_id` int(11)/usr/local/rvm/gems/ruby-2.1.5/gems/activerecord-4.2.0/lib/active_record/connection_adapters/abstract_mysql_adapter.rb:299:in `query'
/usr/local/rvm/gems/ruby-2.1.5/gems/activerecord-4.2.0/lib/active_record/connection_adapters/abstract_mysql_adapter.rb:299:in `block in execute'
/usr/local/rvm/gems/ruby-2.1.5/gems/activerecord-4.2.0/lib/active_record/connection_adapters/abstract_adapter.rb:466:in `block in log'
/usr/local/rvm/gems/ruby-2.1.5/gems/activesupport-4.2.0/lib/active_support/notifications/instrumenter.rb:20:in `instrument'
/usr/local/rvm/gems/ruby-2.1.5/gems/activerecord-4.2.0/lib/active_record/connection_adapters/abstract_adapter.rb:460:in `log'
/usr/local/rvm/gems/ruby-2.1.5/gems/activerecord-4.2.0/lib/active_record/connection_adapters/abstract_mysql_adapter.rb:299:in `execute'
/usr/local/rvm/gems/ruby-2.1.5/gems/activerecord-4.2.0/lib/active_record/connection_adapters/mysql2_adapter.rb:231:in `execute'
/usr/local/rvm/gems/ruby-2.1.5/gems/activerecord-4.2.0/lib/active_record/connection_adapters/abstract/schema_statements.rb:381:in `add_column'
/usr/local/rvm/gems/ruby-2.1.5/gems/activerecord-4.2.0/lib/active_record/migration.rb:662:in `block in method_missing'
/usr/local/rvm/gems/ruby-2.1.5/gems/activerecord-4.2.0/lib/active_record/migration.rb:632:in `block in say_with_time'
/usr/local/rvm/gems/ruby-2.1.5/gems/activerecord-4.2.0/lib/active_record/migration.rb:632:in `say_with_time'
/usr/local/rvm/gems/ruby-2.1.5/gems/activerecord-4.2.0/lib/active_record/migration.rb:652:in `method_missing'
/usr/share/redmine-3.0.1/plugins/redmine_dmsf/db/migrate/20141013102501_remove_project_from_revision.rb:27:in `down'
/usr/local/rvm/gems/ruby-2.1.5/gems/activerecord-4.2.0/lib/active_record/migration.rb:609:in `exec_migration'
/usr/local/rvm/gems/ruby-2.1.5/gems/activerecord-4.2.0/lib/active_record/migration.rb:590:in `block (2 levels) in migrate'
/usr/local/rvm/gems/ruby-2.1.5/gems/activerecord-4.2.0/lib/active_record/migration.rb:589:in `block in migrate'
/usr/local/rvm/gems/ruby-2.1.5/gems/activerecord-4.2.0/lib/active_record/connection_adapters/abstract/connection_pool.rb:292:in `with_connection'
/usr/local/rvm/gems/ruby-2.1.5/gems/activerecord-4.2.0/lib/active_record/migration.rb:588:in `migrate'
/usr/local/rvm/gems/ruby-2.1.5/gems/activerecord-4.2.0/lib/active_record/migration.rb:765:in `migrate'
/usr/local/rvm/gems/ruby-2.1.5/gems/activerecord-4.2.0/lib/active_record/migration.rb:995:in `block in execute_migration_in_transaction'
/usr/local/rvm/gems/ruby-2.1.5/gems/activerecord-4.2.0/lib/active_record/migration.rb:1043:in `ddl_transaction'
/usr/local/rvm/gems/ruby-2.1.5/gems/activerecord-4.2.0/lib/active_record/migration.rb:994:in `execute_migration_in_transaction'
/usr/local/rvm/gems/ruby-2.1.5/gems/activerecord-4.2.0/lib/active_record/migration.rb:956:in `block in migrate'
/usr/local/rvm/gems/ruby-2.1.5/gems/activerecord-4.2.0/lib/active_record/migration.rb:952:in `each'
/usr/local/rvm/gems/ruby-2.1.5/gems/activerecord-4.2.0/lib/active_record/migration.rb:952:in `migrate'
/usr/local/rvm/gems/ruby-2.1.5/gems/activerecord-4.2.0/lib/active_record/migration.rb:827:in `down'
/usr/local/rvm/gems/ruby-2.1.5/gems/activerecord-4.2.0/lib/active_record/migration.rb:802:in `migrate'
/usr/share/redmine-3.0.1/lib/redmine/plugin.rb:474:in `migrate_plugin'
/usr/share/redmine-3.0.1/lib/redmine/plugin.rb:446:in `migrate'
/usr/share/redmine-3.0.1/lib/redmine/plugin.rb:457:in `migrate'
/usr/share/redmine-3.0.1/lib/tasks/redmine.rake:127:in `block (3 levels) in <top (required)>'
/usr/local/rvm/gems/ruby-2.1.5/bin/ruby_executable_hooks:15:in `eval'
/usr/local/rvm/gems/ruby-2.1.5/bin/ruby_executable_hooks:15:in `<main>'
Tasks: TOP => redmine:plugins:migrate
(See full trace by running task with --trace)
~~~

**Comment by picman** [comment]
That's strange. The column shouldn't be there. Please remove it manually prior the migration:

```sql
ALTER TABLE dmsf_file_revisions DROP column project_id;
```
