### ISSUE TITLE
Deleted folder (still in trash) results in errors while accessing parent folder via webdav

### ISSUE THREAD

**Issue by rg-artcom** [danmunn/redmine_dmsf#404]
When a folder is deleted (via webinterface) but still kept in the trash a client can not  use the parent directory via webdav volume. Tested with nautilus (linux) and finder (osx). Eg. under Linux there will be just an "internal server error" dialog when trying to access the parent folder of the deleted folder. After deleting the folder from the DMSF Trash it works fine.

E.g.
/foo/bar/ -> deleted
/foo/ -> can't be listed in webdav client (server error)

**Comment by picman** [comment]
Fixed. Thank you for the bug report.

**Comment by rg-artcom** [comment]
Hi, thank you for the patch.  But sorry, for me it looks like the patch does not fix the problem. I changed the line 135 as shown in the commit f9db08b8fd0bdce88b95f8588dcc1757c962cda3 and rebooted the VM. But the problem is still there. The code we use is the dmsf 1.5.1 stable and not a current checkout of the git repo with redmine 2.6.4 and ruby 2.0.0-p643.

**Comment by picman** [comment]
The relevant commit for 1.5.1 is https://github.com/danmunn/redmine_dmsf/commit/294e39836cb55a6dde13e968b23a0ad97e0b08a8
You can leave the code as it is, the only change which should solve your problem is as follows:

``` ruby
lib/redmine_dmsf/webdav/dmsf_resource.rb - line 57

return @children if @children
         @children = []
         return [] unless collection?
-        folder.subfolders.map do |p|
+        folder.subfolders.visible.map do |p|
           @children.push child(p.title)
         end
         folder.files.visible.map do |p|
```

**Comment by rg-artcom** [comment]
Thank you, now it's fixed.
